[package]
name = "hiker"
version = "0.1.0"
authors = ["sandbox"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
strict = [] # Treat warnings as a build error.
